exclude: models
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --config
          - .code_quality/pyproject_black.toml
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --config=.code_quality/.flake8
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.10
    hooks:
      - id: pylint
        args: [--ignore-patterns=^test, --rcfile=.code_quality/.pylintrc, '--disable=E1120,C0114,C0116,R0913,W0511,W0223,W0613']
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - -s
          - B101,B301,B403,B404,B602
          - -c
          - .code_quality/bandit.yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^tests/
        args:
          - --config-file=.code_quality/mypy.ini
  -   repo: https://github.com/pycqa/pydocstyle
      rev: 4.0.0  # pick a git hash / tag to point to
      hooks:
      -   id: pydocstyle
